### ISSUE TITLE
Max recv buffer size reached, dropping for user Plumble_User seq: 11484

### ISSUE THREAD

**Issue by simonduf** [BananaHemic/Mumble-Unity#22] opened 2018-12-07 02:58 UTC
I ran the example scene and everything worked as expected.
The sound quality feels good!

But after a while when receiving there is a warning on the screen and the sequence number increase:
...
Max recv buffer size reached, dropping for user Plumble_User seq: 1708
Max recv buffer size reached, dropping for user Plumble_User seq: 1710
Max recv buffer size reached, dropping for user Plumble_User seq: 1740
Max recv buffer size reached, dropping for user Plumble_User seq: 1742
...

This happens in the AudioDecodingBuffer but the sound still work and the sound is clear.
There is a red line in the editor graph that is correlated with the warning message, close to be continuous after the first warning. 

The audio is transmitted from a plumble (android client) continuously. Whenever the transmission is stopped, the counter reset.

Should the data dropped affect the output audio?
Is that warning important?

I am currently in unity 2018.2 and using 
mumur 1.2.19
Client version 1.2.5 (Android: Plumble Free 3.2.0)

**Comment by Bananahavoc** [comment] 2018-12-07 06:15
This also happens to me, and to be honest I'm not certain what the cause is.
I know that this happens whenever the audio isn't being pulled fast enough, like during frame drops when the CPU or GPU choke, but it also seems like it may occur in periods when the application is hitting the target framerate.

> The audio is transmitted from a plumble (android client) continuously. Whenever the transmission is stopped, the counter reset.
That number correlates to the audio packet sent from the android client, and is expected to increase monotonically.

> Should the data dropped affect the output audio?
Yes, it should, but I haven't observed audio corruption occurring at the same time as this log message.

I can't take a deeper look right now, but if you are able to do any deeper research into this problem I'd be happy to assist in any way I can

**Comment by simonduf** [comment] 2018-12-07 14:27
Retested at work this morning and no sign of the warning using the same computer and cellphone! Only the network infrastructure changed. Murmur is running locally on my pc.

I was a 100fps when testing, with only the demo scene and most of the cpu time was the vsync.

I will continue the integration and look for anything that could help.

**Comment by simonduf** [comment] 2018-12-08 17:35
Tested again at home, and I am unable to reproduce. Maybe rebooting my pc or unity "solved" the error.

I did get a few "Crypt: 4"  error but that seems unrelated
``
Crypt: 4
UnityEngine.Debug:LogError(Object)
Mumble.CryptState:Decrypt(Byte[], Int32) (at Assets/Mumble-Unity/Scripts/CryptState.cs:274)
``

I suggest closing the issue, and I will post update if I'm able to reproduce at some point. 

Thank you,

Simon

**Comment by Bananahavoc** [comment] 2018-12-08 19:35
I'm going to leave this open for now, in case anyone experiences this problem again

**Comment by Bananahavoc** [comment] 2019-01-10 18:55
I believe the "Crypt: 4" issue was a threading issue from mono's implementation of AesManaged. We now hold a lock whenever interacting with the CryptState in anyway, which seemed to improve the issue.
The "Max Recv..." log previously happened a lot, because buffers dropped due to max recv buffer where re-inserted by decoding a null packet in Opus. This caused the buffer to continually overflow, causing some audio jitter and that log.

Both should now be fixed in 028f713

**Closed as completed by Bananahavoc** 2019-01-10 18:55 UTC
